//************************************
// OECS, G5, Ch2 related component for Z demo
//
//************************************
// Grade 5 - Addition
import D_G5_MA_A1 from "./demoDir/D_G5_MA_A1.svelte"; //3 digit, 2 number, addtion, no regrouping 
import D_G5_MA_A2 from "./demoDir/D_G5_MA_A2.svelte"; //3 digit, 2 number, addtion, regrouping included
import D_G5_MA_A3 from "./demoDir/D_G5_MA_A3.svelte"; //4 digit, 2 number, addtion, no regrouping
import D_G5_MA_A4 from "./demoDir/D_G5_MA_A4.svelte"; //4 digit, 2 number, addtion, regrouping included

import D_G5_MA_B1 from "./demoDir/D_G5_MA_B1.svelte"; //3 digit, 2 number, subtraction, no borrowing 
import D_G5_MA_B2 from "./demoDir/D_G5_MA_B2.svelte"; //3 digit, 2 number, subtraction, borrowing included
import D_G5_MA_B3 from "./demoDir/D_G5_MA_B3.svelte"; //4 digit, 2 number, subtraction, no borrowing
import D_G5_MA_B4 from "./demoDir/D_G5_MA_B4.svelte"; //4 digit, 2 number, subtraction, regrouping included

//eaxmples for section 2.2.1
import D_G5_MA_EXc221a from "./demoDir/D_G5_MA_EXc221a.svelte"; //example 'a' from ch2, section 2.2.1
import D_G5_MA_EXc221b from "./demoDir/D_G5_MA_EXc221b.svelte"; //example 'b' from ch2, section 2.2.1
import D_G5_MA_EXc221c from "./demoDir/D_G5_MA_EXc221c.svelte"; //example 'c' from ch2, section 2.2.1
import D_G5_MA_EXc221d from "./demoDir/D_G5_MA_EXc221d.svelte"; //example 'd' from ch2, section 2.2.1

//eaxmples for section 2.2.2
import D_G5_MA_EXc222a from "./demoDir/D_G5_MA_EXc222a.svelte"; //example 'a' from ch2, section 2.2.1
import D_G5_MA_EXc222b from "./demoDir/D_G5_MA_EXc222b.svelte"; //example 'b' from ch2, section 2.2.1
import D_G5_MA_EXc222c from "./demoDir/D_G5_MA_EXc222c.svelte"; //example 'c' from ch2, section 2.2.1
import D_G5_MA_EXc222d from "./demoDir/D_G5_MA_EXc222d.svelte"; //example 'd' from ch2, section 2.2.1

//eaxmples for section 2.2.3
import D_G5_MA_EXc223a from "./demoDir/D_G5_MA_EXc223a.svelte"; //example 'a' from ch2, section 2.2.1
import D_G5_MA_EXc223b from "./demoDir/D_G5_MA_EXc223b.svelte"; //example 'b' from ch2, section 2.2.1
import D_G5_MA_EXc223c from "./demoDir/D_G5_MA_EXc223c.svelte"; //example 'c' from ch2, section 2.2.1
import D_G5_MA_EXc223d from "./demoDir/D_G5_MA_EXc223d.svelte"; //example 'd' from ch2, section 2.2.1

//eaxmples for section 2.3.1
import D_G5_MA_EXc231a from "./demoDir/D_G5_MA_EXc231a.svelte"; //example 'a' from ch2, section 2.2.1
import D_G5_MA_EXc231b from "./demoDir/D_G5_MA_EXc231b.svelte"; //example 'b' from ch2, section 2.2.1
import D_G5_MA_EXc231c from "./demoDir/D_G5_MA_EXc231c.svelte"; //example 'c' from ch2, section 2.2.1
import D_G5_MA_EXc231d from "./demoDir/D_G5_MA_EXc231d.svelte"; //example 'd' from ch2, section 2.2.1
import D_G5_MA_EXc231e from "./demoDir/D_G5_MA_EXc231e.svelte"; //example 'e' from ch2, section 2.2.1
import D_G5_MA_EXc231f from "./demoDir/D_G5_MA_EXc231f.svelte"; //example 'f' from ch2, section 2.2.1
import D_G5_MA_EXc231g from "./demoDir/D_G5_MA_EXc231g.svelte"; //example 'g' from ch2, section 2.2.1
import D_G5_MA_EXc231h from "./demoDir/D_G5_MA_EXc231h.svelte"; //example 'h' from ch2, section 2.2.1
import D_G5_MA_EXc231i from "./demoDir/D_G5_MA_EXc231i.svelte"; //example 'i' from ch2, section 2.2.1
import D_G5_MA_EXc231j from "./demoDir/D_G5_MA_EXc231j.svelte"; //example 'j' from ch2, section 2.2.1
import D_G5_MA_EXc231k from "./demoDir/D_G5_MA_EXc231k.svelte"; //example 'k' from ch2, section 2.2.1
import D_G5_MA_EXc231l from "./demoDir/D_G5_MA_EXc231l.svelte"; //example 'l' from ch2, section 2.2.1

import D_MN_MA_NL1 from './demoDir/D_MN_MA_NL1.svelte'; //0-10 adding manipulative using numberline
import D_MN_MA_NL2 from './demoDir/D_MN_MA_NL2.svelte'; //0-20 adding manipulative using numberline


//************************************
// Counting related Identifiers
//************************************
export const D_TASK_START_ID = 0; 

// Grade 5 - Adding 
export const ID_D_G5_MA_A1 = D_TASK_START_ID; //3 digit addition, no regrouping, 2 operands
export const ID_D_G5_MA_A2 = ID_D_G5_MA_A1 +1; //3 digit addition, includes regrouping, 2 operands
export const ID_D_G5_MA_A3 = ID_D_G5_MA_A2 +1; //4 digit addition, no regrouping, 2 operands
export const ID_D_G5_MA_A4 = ID_D_G5_MA_A3 +1; //4 digit addition, includes regrouping, 2 operands

// Grade 5 - Subtracting 
export const ID_D_G5_MA_B1 = ID_D_G5_MA_A4 +1; //3 digit addition, no regrouping, 2 operands
export const ID_D_G5_MA_B2 = ID_D_G5_MA_B1 +1; //3 digit addition, includes regrouping, 2 operands
export const ID_D_G5_MA_B3 = ID_D_G5_MA_B2 +1; //4 digit addition, no regrouping, 2 operands
export const ID_D_G5_MA_B4 = ID_D_G5_MA_B3 +1; //4 digit addition, includes regrouping, 2 operands

export const ID_D_G5_MA_EXc221a = ID_D_G5_MA_B4 +1;     //example 'a', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc221b = ID_D_G5_MA_EXc221a +1; //example 'b', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc221c = ID_D_G5_MA_EXc221b +1; //example 'c', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc221d = ID_D_G5_MA_EXc221c +1; //example 'd', Ch2, sect 2.2.1.

export const ID_D_G5_MA_EXc222a = ID_D_G5_MA_EXc221d +1;     //example 'a', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc222b = ID_D_G5_MA_EXc222a +1; //example 'b', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc222c = ID_D_G5_MA_EXc222b +1; //example 'c', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc222d = ID_D_G5_MA_EXc222c +1; //example 'd', Ch2, sect 2.2.1.

export const ID_D_G5_MA_EXc223a = ID_D_G5_MA_EXc222d +1;     //example 'a', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc223b = ID_D_G5_MA_EXc223a +1; //example 'b', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc223c = ID_D_G5_MA_EXc223b +1; //example 'c', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc223d = ID_D_G5_MA_EXc223c +1; //example 'd', Ch2, sect 2.2.1.

export const ID_D_G5_MA_EXc231a = ID_D_G5_MA_EXc223d +1; //example 'a', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231b = ID_D_G5_MA_EXc231a +1; //example 'b', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231c = ID_D_G5_MA_EXc231b +1; //example 'c', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231d = ID_D_G5_MA_EXc231c +1; //example 'd', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231e = ID_D_G5_MA_EXc231d +1; //example 'e', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231f = ID_D_G5_MA_EXc231e +1; //example 'f', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231g = ID_D_G5_MA_EXc231f +1; //example 'G', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231h = ID_D_G5_MA_EXc231g +1; //example 'h', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231i = ID_D_G5_MA_EXc231h +1; //example 'i', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231j = ID_D_G5_MA_EXc231i +1; //example 'j', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231k = ID_D_G5_MA_EXc231j +1; //example 'k', Ch2, sect 2.2.1.
export const ID_D_G5_MA_EXc231l = ID_D_G5_MA_EXc231k +1; //example 'l', Ch2, sect 2.2.1.

// math manipulatives
export const ID_D_MN_MA_NL1 = ID_D_G5_MA_EXc231l + 1 ; //0-10 adding math manipulative using numberline
export const ID_D_MN_MA_NL2 = ID_D_MN_MA_NL1 + 1 ; //0-20 adding math manipulative using numberline

export const ID_D_TASK_END_ID = ID_D_MN_MA_NL2;


//******************************* */
// Activities List 
// all Z demo related components only
//
//******************************* */
export const DEMO_TASKS_LIST = [
  {
    id: ID_D_G5_MA_A1,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_A1,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_A1,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "3dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_A2,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_A2,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_A2,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_A3,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_A3,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_A3,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_A4,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_A4,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_A4,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_B1,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_B1,
    act_text: "Subtracting without borrowing",
    comp: D_G5_MA_B1,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Subtract the second 3-digit number from first (no borrowing)',
    question: 'Subtract: ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "3dig_NoBorrow",
  },
  {
    id: ID_D_G5_MA_B2,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_B2,
    act_text: "Subtracting with borrowing",
    comp: D_G5_MA_B2,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Subtract the second 3-digit number from first (with borrowing)',
    question: 'Subtract: ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "borrow",
  },
  {
    id: ID_D_G5_MA_B3,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_B3,
    act_text: "Subtracting without borrowing",
    comp: D_G5_MA_B3,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Subtract the second 4-digit number from first (no borrowing)',
    question: 'Subtract: ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoBorrow",
  },
  {
    id: ID_D_G5_MA_B4,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_B4,
    act_text: "Subtracting with borrowing",
    comp: D_G5_MA_B4,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Subtract the second 4-digit number from first (with borrowing)',
    question: 'Subtract: ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "borrow",
  },
  {
    id: ID_D_G5_MA_EXc221a,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc221a,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc221a,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "3dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc221b,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc221b,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc221b,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "3dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc221c,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc221c,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc221c,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "3dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc221d,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc221d,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc221d,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "3dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc222a,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc222a,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_EXc222a,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_EXc222b,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc222b,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_EXc222b,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_EXc222c,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc222c,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_EXc222c,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_EXc222d,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc222d,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_EXc222d,
    lowValue: 100,
    highValue: 999,
    operandCnt: 2,
    heading: 'Add the two 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_EXc223a,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc223a,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_EXc223a,
    lowValue: 100,
    highValue: 999,
    operandCnt: 3,
    heading: 'Add the three 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },  
  {
    id: ID_D_G5_MA_EXc223b,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc223b,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_EXc223b,
    lowValue: 100,
    highValue: 999,
    operandCnt: 3,
    heading: 'Add the three 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_EXc223c,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc223c,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_EXc223c,
    lowValue: 100,
    highValue: 999,
    operandCnt: 3,
    heading: 'Add the three 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_EXc223d,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc223d,
    act_text: "Adding with regrouping",
    comp: D_G5_MA_EXc223d,
    lowValue: 100,
    highValue: 999,
    operandCnt: 3,
    heading: 'Add the three 3-digit numbers with regrouping',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "regroup",
  },
  {
    id: ID_D_G5_MA_EXc231a,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231a,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231a,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231b,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231b,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231b,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231c,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231c,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231c,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231d,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231d,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231d,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231e,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231e,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231e,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231f,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231f,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231f,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231g,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231g,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231g,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231h,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231h,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231h,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231i,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231i,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231i,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231j,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231j,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231j,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231k,
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231k,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231k,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_G5_MA_EXc231l,  //32 in demo
    grade: 5,
    subject: "math",
    act_ID: ID_D_G5_MA_EXc231l,
    act_text: "Adding without regrouping",
    comp: D_G5_MA_EXc231l,
    lowValue: 1001,
    highValue: 9999,
    operandCnt: 2,
    heading: 'Add the two 4-digit numbers (no regrouping)',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "4dig_NoRegroup",
  },
  {
    id: ID_D_MN_MA_NL1,
    grade: 5,
    subject: "math",
    act_ID: ID_D_MN_MA_NL1,
    act_text: "Adding on Numberline",
    comp: D_MN_MA_NL1,
    lowValue: 0,
    highValue: 10,
    operandCnt: 2,
    heading: 'Add the two 1-digit numbers on Numberline',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "MN_NL1",
  },
  {
    id: ID_D_MN_MA_NL2,
    grade: 5,
    subject: "math",
    act_ID: ID_D_MN_MA_NL2,
    act_text: "Adding on Numberline",
    comp: D_MN_MA_NL2,
    lowValue: 0,
    highValue: 20,
    operandCnt: 2,
    heading: 'Add the two 1-digit numbers on Numberline',
    question: 'Add : ',
    question_type: 'input',
    img_prcnt:"30%",
    img_type: "pics",
    inputMethod: "textbox",
    max_button: 4, 
    operation: "MN_NL2",
  },
];

